# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The project name.
project_name: updater

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - # The main binary to build.
    main: ./cmd/updater
    # GOOS and GOARCH to build for.
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # CGO_ENABLED=0 is required for cross-compilation.
    env:
      - CGO_ENABLED=0

archives:
  - # The format of the archive.
    format: tar.gz
    # This is a list of format overrides for specific platforms.
    format_overrides:
      - goos: windows
        format: zip

checksum:
  # The name of the checksums file.
  name_template: 'checksums.txt'

snapshot:
  # The name of the snapshot release.
  name_template: "{{ incpatch .Version }}-next"

changelog:
  # Sort the changelog by commit date.
  sort: asc
  # Filter out certain commit messages.
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - # The name of the Homebrew formula.
    name: updater
    # The GitHub repository to push the formula to.
    tap:
      owner: your-username
      name: homebrew-tap
    # The commit author.
    commit_author:
      name: goreleaserbot
      email: goreleaser@example.com
    # The homepage of the project.
    homepage: "https://github.com/your-username/updater"
    # A description of the project.
    description: "A demo CLI for the updater"
    # The license of the project.
    license: "MIT"
